import uiScriptLocale

window = {

	"x" : 0,
	"y" : 0,

	"width" : SCREEN_WIDTH,
	"height" : SCREEN_HEIGHT,

	"children" :
	(
		{
			"name" : "BackGround",
			"type" : "expanded_image",
			"x" : 0,
			"y" : 0,
			"image" : "d:/locale/it/improveload/bg2.png",
			"x_scale" : float(SCREEN_WIDTH) / 1920.0,
			"y_scale" : float(SCREEN_HEIGHT) / 1080.0,
		},
		{
			"name" : "AnimBackGround",
			"type" : "ani_image",
			"x" : SCREEN_WIDTH/2 - 373,
			"y" : SCREEN_HEIGHT/2 - 210,
			"delay" : 2,
			"images":
			(
				"dunno_/Untitled-100.png",
				"dunno_/Untitled-101.png",
				"dunno_/Untitled-102.png",
				"dunno_/Untitled-103.png",
				"dunno_/Untitled-104.png",
				"dunno_/Untitled-105.png",
				"dunno_/Untitled-106.png",
				"dunno_/Untitled-107.png",
				"dunno_/Untitled-108.png",
				"dunno_/Untitled-109.png",
				"dunno_/Untitled-110.png",
				"dunno_/Untitled-111.png",
				"dunno_/Untitled-112.png",
				"dunno_/Untitled-113.png",
				"dunno_/Untitled-114.png",
				"dunno_/Untitled-115.png",
				"dunno_/Untitled-116.png",
				"dunno_/Untitled-117.png",
				"dunno_/Untitled-118.png",
				"dunno_/Untitled-119.png",
				"dunno_/Untitled-120.png",
				"dunno_/Untitled-121.png",
				"dunno_/Untitled-122.png",
				"dunno_/Untitled-123.png",
				"dunno_/Untitled-124.png",
				"dunno_/Untitled-125.png",
				"dunno_/Untitled-126.png",
				"dunno_/Untitled-127.png",
				"dunno_/Untitled-128.png",
				"dunno_/Untitled-129.png",
				"dunno_/Untitled-130.png",
				"dunno_/Untitled-131.png",
				"dunno_/Untitled-132.png",
				"dunno_/Untitled-133.png",
				"dunno_/Untitled-134.png",
				"dunno_/Untitled-135.png",
				"dunno_/Untitled-136.png",
				"dunno_/Untitled-137.png",
				"dunno_/Untitled-138.png",
				"dunno_/Untitled-139.png",
				"dunno_/Untitled-140.png",
				"dunno_/Untitled-141.png",
				"dunno_/Untitled-142.png",
				"dunno_/Untitled-143.png",
				"dunno_/Untitled-144.png",
				"dunno_/Untitled-145.png",
				"dunno_/Untitled-146.png",
				"dunno_/Untitled-147.png",
				"dunno_/Untitled-148.png",
				"dunno_/Untitled-149.png",
				"dunno_/Untitled-150.png",
				"dunno_/Untitled-151.png",
				"dunno_/Untitled-152.png",
				"dunno_/Untitled-153.png",
				"dunno_/Untitled-154.png",
				"dunno_/Untitled-155.png",
				"dunno_/Untitled-156.png",
				"dunno_/Untitled-157.png",
				"dunno_/Untitled-158.png",
				"dunno_/Untitled-159.png",
			),
		},
	),
}
